### PR TITLE
Use shared descriptor pools for descriptor sets and add synchronization

### LINKED ISSUE #118: Rework command buffer submitting
```
ERROR:: [DS] Object: 0x7f2b421a6400 | You are adding vkQueueSubmit() to command buffer 0x7f2b421a6400 that is invalid because bound DescriptorSet 0x1602 was destroyed or updated.
```
This comes from `bind_locals` and `bind_textures`.
Currently we batching all the commands and submitting at the end, before calling present.
Instead of this, we should submit after a render pass (in renderer.rs' `draw_tile_frame`).

### PR DESCRIPTION
**Pull request by dati91**
Fixes #118 

With this, we introduce magic numbers for maximum descriptor sets and sampler/image counts, which is not that great.
Also we get the descriptor set layouts for the pool from specific shaders. We should rework our build.rs logic to match our new requirements.

### CODE REVIEW

File: webrender/src/device.rs [hunk 1]
```diff
@@ -1074,25 +1076,24 @@ impl<B: hal::Backend> UniformBuffer<B> {
...
     pub locals_buffer: UniformBuffer<B>,
     shader_name: String,
+    shader_kind: ShaderKind,
 }
 
 impl<B: hal::Backend> Program<B> {
     pub fn create(
         pipeline_requirements: PipelineRequirements,
         device: &B::Device,
+        descriptor_set_layout: &B::DescriptorSetLayout,
```
Comment (kvark) [inline webrender/src/device.rs]: we should probably pass the pipeline layout in here, not descriptor set layout

File: webrender/src/device.rs [hunk 2]
```diff
@@ -1629,6 +1619,166 @@ impl<B: hal::Backend> RenderPass<B> {
...
+            descriptor_set_layout,
+            current_descriptor_set_id: 0,
+            max_descriptor_set_size: max_size,
+        };
+        dp.next();
+        dp.reset();
+        dp
+    }
+
+    pub fn get_descriptor_set(&mut self) -> &B::DescriptorSet {
```
Comment (kvark) [inline webrender/src/device.rs]: nit: the Rust API guidelines say that simple accessors shouldn't have "get_" prefix

File: webrender/src/device.rs [hunk 3]
```diff
@@ -1629,6 +1619,166 @@ impl<B: hal::Backend> RenderPass<B> {
...
+            );
+        let descriptor_set_layout = device.create_descriptor_set_layout(&descriptor_set_layout);
+        let mut dp = DescPool {
+            descriptor_pool,
+            descriptor_set: vec!(),
+            descriptor_set_layout,
+            current_descriptor_set_id: 0,
+            max_descriptor_set_size: max_size,
+        };
+        dp.next();
```
Comment (kvark) [inline webrender/src/device.rs]: why is `next` + `reset` needed here?

File: webrender/src/device.rs [hunk 4]
```diff
@@ -2015,6 +2180,7 @@ impl<B: hal::Backend> Device<B> {
         self.bound_sampler = [TextureFilter::Linear; 16];
         self.bound_read_fbo = DEFAULT_READ_FBO;
         self.bound_draw_fbo = DEFAULT_DRAW_FBO;
+        self.descriptor_pools.reset();
```
Comment (kvark) [inline webrender/src/device.rs]: we've got to be careful with this. IIRC, reset state is called at least every frame. We are not allowed to re-write the descriptor sets that the GPU is still working on. Resetting the pool here would make us grab a descriptor set that is still in flight.

File: webrender/src/device.rs [hunk 5]
```diff
@@ -1374,19 +1364,19 @@ impl<B: hal::Backend> Program<B> {
         ]);
     }
 
-    pub fn bind_texture(&mut self, device: &B::Device, image: &ImageCore<B>, sampler: &B::Sampler, binding: &'static str) {
+    fn bind_texture(&mut self, device: &B::Device, set: &B::DescriptorSet, image: &ImageCore<B>, sampler: &B::Sampler, binding: &'static str) {
```
Comment (kvark) [inline webrender/src/device.rs]: while it might be OK to do this *for now*, in the long run we need to upstream some notion of descriptor sets, so that their recycling is cleaner, maybe even shove the responsibility to the renderer.

**Comment by kvark** [comment]
Thanks for taking a stab at this, @dati91 ! I think it's a good step forward, just need to make it correct w.r.t. respecting the lifetime of those descriptors on GPU

**Comment by dati91** [comment]
Sorry for the long delay. This is almost done, and performance wise better than my previous attempts. (Note: I don't have exact numbers, but after i figure out the remaining issues, i can measure things properly)

There are 2 things remaining:
- It only works on vulkan
  - My guess is DX12 doesn't like my [high descriptor numbers](https://github.com/dati91/webrender/commit/268a4e034fed207c21e3f914a6b2a220d0ba555f#diff-d058594280164bb23d9b1ca25ba9fe79R1885)
  - `gfx_backend_dx12::device::{{impl}}::create_descriptor_pool<slice<gfx_hal::pso::descriptor::DescriptorRangeDesc>*>`
  - `thread main panicked at called Option::unwrap() on a None value`
- I have a validation Layer error
  - ERROR [DS] Object: 0x0 | Command Buffer 0x1ac10cd95b8 is already in use and is not marked for simultaneous use. The spec valid usage text states 'If any element of the pCommandBuffers member of any element of pSubmits was not recorded with the VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT, it must not be in the pending state.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkQueueSubmit-pCommandBuffers-00071)

And the error comes from creating resources and throwing them away because we [reset the command pool](https://github.com/dati91/webrender/commit/268a4e034fed207c21e3f914a6b2a220d0ba555f#diff-d058594280164bb23d9b1ca25ba9fe79R3670) before entering the draw phase.
I already [submitting things to the gpu](https://github.com/dati91/webrender/commit/268a4e034fed207c21e3f914a6b2a220d0ba555f#diff-d058594280164bb23d9b1ca25ba9fe79R3725) when [creating renderer and device](https://github.com/dati91/webrender/commit/268a4e034fed207c21e3f914a6b2a220d0ba555f#diff-f5062b694b9fe53fc1757ed483d577d9R1757).
I still have to find a good way to submit the remaining resource created before the first render call.

**Comment by kvark** [comment]
>And the error comes from creating resources and throwing them away because we reset the command pool before entering the draw phase.
I already submitting things to the gpu when creating renderer and device.
I still have to find a good way to submit the remaining resource created before the first render call.

You can't dismiss the command buffers or any resources they use upon submitting them to the queue. This is not GL :) You are only allowed to reset the command pool after the GPU is done with those buffers/resources.

**Comment by dati91** [comment]
I have one corner case to handle, when freeing a texture, which is still in flight. 
Note: i had to lower the numbers to get the dx12 work again, but with this number servo will run out descriptor sets pretty quickly. But for wrench these numbers are enough.

**Comment by dati91** [comment]
Turn out, that the last_frame_used is only set when `init_texture` called. And we need to update it when we bind it in a frame as well.
